<h2>Mis Manuscritos</h2>

<div class="table-responsive">
  <table class="table table-bordered">
      <thead>
        <th>#</th>
        <th>Revista</th>
        <th>Titulo</th>
        <th>Autores</th>
        <th>Estatus</th>
      </thead>
      
      <tbody>
          <tr>
              <td>1</td>
              <td>Ciencias</td>
              <td>Evidencia citog&eacute;nica de c&eacute;lulas tumorales circulantes en sangre perif&eacute;ricas de mujeres venezolanas con c&aacute;ncer de mama</td>
              <td>Autores</td>
              <td>Esperando revision del Editor</td>
          </tr>
          
      </tbody>
  </table>
    
</div>


